language: node_js
sudo: false
node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "4.4"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "5.7"
  - "5.8"
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - npm -g install npm@latest-2
  - "gem install --version 0.8.9 faraday"
