language: node_js
sudo: false
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "stable"
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - npm -g install npm@latest-2
  - "gem install --version 0.8.9 faraday"
script: "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
