language: node_js
sudo: false
node_js:
  - "4.0"
  - "4.4"
  - "5.0"
  - "stable"
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - npm -g install npm@latest-2
  - "gem install --version 0.8.9 faraday"
